spring:
  liquibase:
    change-log: classpath:/db/master-changelog.xml

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
