version: '3'
services:
  postgres:
    image: 'postgres:latest'
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile-dev
    ports:
      - '8080:80'
  rest:
    build:
      context: ./rest
      dockerfile: Dockerfile-dev
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - TWITTER_CRON_UPDATER=* 0/30 * * * *
      - TWITTER_CONSUMER_KEY=
      - TWITTER_CONSUMER_SECRET=
      - TWITTER_ACCESS_TOKEN=
      - TWITTER_ACCESS_TOKEN_SECRET=
    volumes:
      - C:/Users/nryba/.m2/repository:/root/.m2/repository
      - ./rest:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    # volumes:
    #   - ./client:/app